// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btallyhejhqfpqwaboee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0YWxseWhlamhxZnBxd2Fib2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2Nzc4MjksImV4cCI6MjA4OTI1MzgyOX0.CB7TXgFgRx_CdaUmegCUl9woUFjk7x05CCYs4VNtL5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);