// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukeanoikgltpwyprvjee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZWFub2lrZ2x0cHd5cHJ2amVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDQ3NzIsImV4cCI6MjA2NTU4MDc3Mn0.l0maDiWe_KAK4_lLsVHFGC9c1QykgRHBiWnnmQUqUpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);